export const ProductsData = [
    {
        id: 1,
        name: 'HAVIT HV-G92 Gamepad',
        imageUrl: '/src/assets/controller.png',
        price: '$120',
        oldPrice: '$160',
        discount: '- 40%',
        rating: 4,
        reviews: 88,
    },
    {
        id: 2,
        name: 'AK-900 Wired Keyboard',
        imageUrl: '/src/assets/keyboard.png',
        price: '$960',
        oldPrice: '$1160',
        discount: '- 35%',
        rating: 75,
        reviews: 182,
    },
    {
        id: 3,
        name: 'IPS LCD Gaming Monitor',
        imageUrl: '/src/assets/monitor.png',
        price: '$370',
        oldPrice: '$400',
        discount: '- 30%',
        rating: 40,
        reviews: 67,
    },
    {
        id: 4,
        name: 'S-Series Comfort Chair',
        imageUrl: '/src/assets/chair.png',
        price: '$375',
        oldPrice: '$400',
        discount: '- 25%',
        rating: 98,
        reviews: 43,
    },
    {
        id: 5,
        name: 'Gaming Headset Pro',
        imageUrl: '/src/assets/monitor.png',
        price: '$150',
        oldPrice: '$200',
        discount: '- 20%',
        rating: 85,
        reviews: 120,
    },
    {
        id: 6,
        name: 'RGB Gaming Mouse',
        imageUrl: '/src/assets/monitor.png',
        price: '$60',
        oldPrice: '$80',
        discount: '- 25%',
        rating: 90,
        reviews: 200,
    },
    {
        id: 7,
        name: 'Wireless Charging Pad',
        imageUrl: '/src/assets/monitor.png',
        price: '$30',
        oldPrice: '$50',
        discount: '- 40%',
        rating: 70,
        reviews: 150,
    },
    {
        id: 8,
        name: 'Gaming Laptop Stand',
        imageUrl: '/src/assets/monitor.png',
        price: '$45',
        oldPrice: '$60',
        discount: '- 25%',
        rating: 80,
        reviews: 90,
    },
    {
        id: 9,
        name: 'Portable SSD 1TB',
        imageUrl: '/src/assets/monitor.png',
        price: '$100',
        oldPrice: '$120',
        discount: '- 15%',
        rating: 95,
        reviews: 75,
    },
    {
        id: 10,
        name: 'Gaming Desk Mat',
        imageUrl: '/src/assets/monitor.png',
        price: '$20',
        oldPrice: '$30',
        discount: '- 33%',
        rating: 88,
        reviews: 110,
    }

];
